/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./src/components/about-dialog.vue')['default']
    GameHistory: typeof import('./src/components/game-history.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreKeeper: typeof import('./src/components/score-keeper.vue')['default']
    ScoreKeeperMenu: typeof import('./src/components/score-keeper-menu.vue')['default']
    ThemeSwitch: typeof import('./src/components/theme-switch.vue')['default']
  }
}
