/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreKeeper: typeof import('./src/components/score-keeper.vue')['default']
    ScoreKeeperMenu: typeof import('./src/components/score-keeper-menu.vue')['default']
  }
}
